"""add units check constraint

Revision ID: 600375436618
Revises: a763f8747baa
Create Date: 2026-09-21 15:13:05.052611

Hand-written, not autogenerated: Alembic's Postgres reflection doesn't
detect CHECK constraint additions (autogenerate produced only the
spurious `alembic_version` drop/recreate the README's own "Local dev"
section already documents stripping -- no constraint diff at all), so
this mirrors `app.domain.preferences.UserPreferences.__table_args__`
by hand instead.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "600375436618"
down_revision: str | None = "a763f8747baa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_check_constraint(
        "ck_user_preferences_units",
        "user_preferences",
        "units IN ('imperial', 'metric')",
    )


def downgrade() -> None:
    op.drop_constraint("ck_user_preferences_units", "user_preferences", type_="check")
